version: "3.8"

services:
  app-server:
    build: ./backend
    secrets:
      - app_secret
    networks:
      - app-net
    deploy:
      replicas: 3

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - app-server
    networks:
      - app-net

networks:
  app-net:

secrets:
  app_secret:
    file: ./secrets/app_secret.txt